AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  BIMBOEncryptPDFFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: BimboEncryptPDF-Function
      Architectures: [x86_64]
      CodeUri: app/hello/
      Handler: lambda_function.lambda_handler
      Runtime: python3.12
      Timeout: 15
      MemorySize: 256
      LoggingConfig:
        LogFormat: JSON
      Policies:
        - AmazonS3FullAccess
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref BIMBOPDFSourceBucket
            Events: s3:ObjectCreated:*

  BIMBOPDFSourceBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: bimbopdfsourcebucket-16022025

  BIMBOEncryptedPDFBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: bimbopdfsourcebucket-16022025-encrypted

  
  TEENIEEncryptPDFFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: TennieEncryptPDF-Function
      Architectures: [x86_64]
      CodeUri: app/pdf/
      Handler: lambda_function.lambda_handler
      Runtime: python3.12
      Timeout: 15
      MemorySize: 256
      LoggingConfig:
        LogFormat: JSON
      Policies:
        - AmazonS3FullAccess
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref TENNIESourcePDFBucket
            Events: s3:ObjectCreated:*

  TENNIESourcePDFBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: tenniepdfsourcebucket-16022025

  TENNIEEncryptedPDFBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: tenniepdfsourcebucket-16022025-encrypted
